[package]
name = "BC26"
version = "0.1.0"
authors = ["CNLHC <cn_lhc@qq.com>"]
edition = "2018"
[lib]
name = "BC26"
crate-type = ["staticlib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


heapless="0.5.1"

